import React from 'react';
import StartHereBanner from './StartHereBanner';

const PrivacyPolicyPage: React.FC = () => {
  return (
    <div className="bg-[#050b14] min-h-screen pt-20 font-sans text-white">
      <div className="relative bg-[#0a101d] border-b border-white/5 py-16">
          <div className="max-w-4xl mx-auto px-4">
              <h1 className="font-display font-black text-4xl md:text-5xl text-white uppercase tracking-tight mb-4">
                  PRIVACY POLICY
              </h1>
              <p className="text-gray-400 text-sm">Last updated: February 13, 2026</p>
          </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-16">
          <div className="space-y-12 text-gray-300 leading-relaxed text-sm md:text-base">
              
              <p>
                  At Codoen Hosting, we are committed to protecting the privacy and security of our customers' personal information. This Privacy Policy outlines how we collect, use, and safeguard your information when you visit or make a purchase on our website. By using our website, you consent to the practices described in this policy.
              </p>

              <section>
                  <h2 className="font-display font-bold text-2xl text-white mb-4">INFORMATION WE COLLECT</h2>
                  <p className="mb-4">When you visit our website, we may collect certain information about you, including:</p>
                  <ul className="list-disc pl-5 space-y-2 text-gray-400">
                      <li>Personal identification information (such as your name, email address, and phone number) provided voluntarily by you during the registration or checkout process.</li>
                      <li>Payment and billing information necessary to process your orders, including credit card details, which are securely handled by trusted third-party payment processors (e.g., Stripe, PayPal).</li>
                      <li>Browsing information, such as your IP address, browser type, and device information, collected automatically using cookies and similar technologies.</li>
                      <li>Server logs and data generated by your use of our hosting services.</li>
                  </ul>
              </section>

              <section>
                  <h2 className="font-display font-bold text-2xl text-white mb-4">USE OF INFORMATION</h2>
                  <p className="mb-4">We may use the collected information for the following purposes:</p>
                  <ul className="list-disc pl-5 space-y-2 text-gray-400">
                      <li>To process and fulfill your orders, including service provisioning and setup.</li>
                      <li>To communicate with you regarding your purchases, provide customer support, and respond to inquiries or requests.</li>
                      <li>To personalize your shopping experience and present relevant product recommendations and promotions.</li>
                      <li>To improve our website, control panel, and services based on your feedback and usage patterns.</li>
                      <li>To detect and prevent fraud, unauthorized activities, and abuse of our website.</li>
                  </ul>
              </section>

              <section>
                  <h2 className="font-display font-bold text-2xl text-white mb-4">INFORMATION SHARING</h2>
                  <p className="mb-4">
                      We respect your privacy and do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except in the following circumstances:
                  </p>
                  <ul className="list-disc pl-5 space-y-2 text-gray-400">
                      <li>
                          <strong>Trusted service providers:</strong> We may share your information with third-party service providers who assist us in operating our website, processing payments, and delivering services. These providers are contractually obligated to handle your data securely and confidentially.
                      </li>
                      <li>
                          <strong>Legal requirements:</strong> We may disclose your information if required to do so by law or in response to valid legal requests or orders.
                      </li>
                  </ul>
              </section>

              <section>
                  <h2 className="font-display font-bold text-2xl text-white mb-4">DATA SECURITY</h2>
                  <p>
                      We implement industry-standard security measures to protect your personal information from unauthorized access, alteration, disclosure, or destruction. However, please be aware that no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee absolute security.
                  </p>
              </section>

              <section>
                  <h2 className="font-display font-bold text-2xl text-white mb-4">COOKIES AND TRACKING TECHNOLOGIES</h2>
                  <p>
                      We use cookies and similar technologies to enhance your browsing experience, analyze website traffic, and gather information about your preferences and interactions with our website. You have the option to disable cookies through your browser settings, but this may limit certain features and functionality of our website (such as the Client Area).
                  </p>
              </section>

              <section>
                  <h2 className="font-display font-bold text-2xl text-white mb-4">CHANGES TO THE PRIVACY POLICY</h2>
                  <p>
                      We reserve the right to update or modify this Privacy Policy at any time. Any changes will be posted on this page with a revised "last updated" date. We encourage you to review this Privacy Policy periodically to stay informed about how we collect, use, and protect your information.
                  </p>
              </section>

              <section>
                  <h2 className="font-display font-bold text-2xl text-white mb-4">CONTACT US</h2>
                  <p>
                      If you have any questions, concerns, or requests regarding our Privacy Policy or the handling of your personal information, please contact us using the ticket system in our client area.
                  </p>
              </section>

          </div>
      </div>

      <StartHereBanner />
    </div>
  );
};

export default PrivacyPolicyPage;